#!/usr/bin/python3
# -*- coding: utf-8 -*-
import argparse
import logging
import sys
from PyQt5.QtWidgets import QApplication
from generator_tools.generatorForm import MapGeneratorForm



def main(args):
  app = QApplication(sys.argv)
  form = MapGeneratorForm(args)
  form.show()
  app.exec_()
  
if __name__ == '__main__':
  parser = argparse.ArgumentParser(description="ChimeraTK mapfile generator", formatter_class=argparse.ArgumentDefaultsHelpFormatter)
  parser.add_argument('--input', type=str, help='XML file created by the XML generator of the ChimeraTK application.')
  parser.add_argument('-d', '--debug', action='store_true', help='Enable debug messages.')
  args = parser.parse_args()
  logLevel = logging.DEBUG if args.debug else logging.INFO
  logging.basicConfig(format='[%(levelname)s]: %(message)s', level=logLevel)
  main(args)