# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historyUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistoryDialog(object):
    def setupUi(self, HistoryDialog):
        HistoryDialog.setObjectName("HistoryDialog")
        HistoryDialog.resize(678, 178)
        self.verticalLayout = QtWidgets.QVBoxLayout(HistoryDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(HistoryDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.historyName = QtWidgets.QLineEdit(HistoryDialog)
        self.historyName.setMinimumSize(QtCore.QSize(500, 0))
        self.historyName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.historyName.setObjectName("historyName")
        self.horizontalLayout.addWidget(self.historyName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(HistoryDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.entriesPerResponse = QtWidgets.QSpinBox(HistoryDialog)
        self.entriesPerResponse.setMinimumSize(QtCore.QSize(0, 0))
        self.entriesPerResponse.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.entriesPerResponse.setMinimum(1)
        self.entriesPerResponse.setMaximum(100000)
        self.entriesPerResponse.setProperty("value", 100)
        self.entriesPerResponse.setObjectName("entriesPerResponse")
        self.horizontalLayout_2.addWidget(self.entriesPerResponse)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(HistoryDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.bufferLength = QtWidgets.QSpinBox(HistoryDialog)
        self.bufferLength.setMinimumSize(QtCore.QSize(0, 0))
        self.bufferLength.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bufferLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bufferLength.setMinimum(2)
        self.bufferLength.setMaximum(1000000000)
        self.bufferLength.setProperty("value", 100)
        self.bufferLength.setObjectName("bufferLength")
        self.horizontalLayout_3.addWidget(self.bufferLength)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(HistoryDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.samplingInterval = QtWidgets.QSpinBox(HistoryDialog)
        self.samplingInterval.setMinimumSize(QtCore.QSize(0, 0))
        self.samplingInterval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.samplingInterval.setPrefix("")
        self.samplingInterval.setMaximum(600000)
        self.samplingInterval.setProperty("value", 1000)
        self.samplingInterval.setObjectName("samplingInterval")
        self.horizontalLayout_4.addWidget(self.samplingInterval)
        self.label_5 = QtWidgets.QLabel(HistoryDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(HistoryDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(HistoryDialog)
        self.buttonBox.accepted.connect(HistoryDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(HistoryDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HistoryDialog)

    def retranslateUi(self, HistoryDialog):
        _translate = QtCore.QCoreApplication.translate
        HistoryDialog.setWindowTitle(_translate("HistoryDialog", "Dialog"))
        self.label.setText(_translate("HistoryDialog", "History setting name:"))
        self.label_2.setText(_translate("HistoryDialog", "Entries per response:"))
        self.entriesPerResponse.setToolTip(_translate("HistoryDialog", "<html><head/><body><p>If a long history is requested by a client this number defines how data is transfered. A large number means big frames are used. A small number means multiple frames are used. They are connected via continuation points and multiple ReadHistoryRequest/ReadHistoryResponse messages are used.</p></body></html>"))
        self.label_3.setText(_translate("HistoryDialog", "Buffer length:"))
        self.bufferLength.setToolTip(_translate("HistoryDialog", "<html><head/><body><p>A ring buffer is used to store the history in memory. This number defines the size of the ring buffer.</p></body></html>"))
        self.label_4.setText(_translate("HistoryDialog", "Sampling interval:"))
        self.samplingInterval.setToolTip(_translate("HistoryDialog", "<html><head/><body><p>This number defines the sampling interval on the server side. If data updates happen faster on the server side this will not be seen by the history.</p></body></html>"))
        self.label_5.setText(_translate("HistoryDialog", "ms"))
