# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LDSUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LDSDialog(object):
    def setupUi(self, LDSDialog):
        LDSDialog.setObjectName("LDSDialog")
        LDSDialog.resize(400, 149)
        self.verticalLayout = QtWidgets.QVBoxLayout(LDSDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.registerLDS = QtWidgets.QCheckBox(LDSDialog)
        self.registerLDS.setObjectName("registerLDS")
        self.verticalLayout.addWidget(self.registerLDS)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(LDSDialog)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.ldsAddress = QtWidgets.QLineEdit(LDSDialog)
        self.ldsAddress.setObjectName("ldsAddress")
        self.horizontalLayout_2.addWidget(self.ldsAddress)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_12 = QtWidgets.QLabel(LDSDialog)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.ldsRegistryName = QtWidgets.QLineEdit(LDSDialog)
        self.ldsRegistryName.setObjectName("ldsRegistryName")
        self.horizontalLayout.addWidget(self.ldsRegistryName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(LDSDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(LDSDialog)
        self.buttonBox.accepted.connect(LDSDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(LDSDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LDSDialog)

    def retranslateUi(self, LDSDialog):
        _translate = QtCore.QCoreApplication.translate
        LDSDialog.setWindowTitle(_translate("LDSDialog", "Dialog"))
        self.registerLDS.setText(_translate("LDSDialog", "Register at LDS"))
        self.label_11.setText(_translate("LDSDialog", "LDS:"))
        self.ldsAddress.setText(_translate("LDSDialog", "opc.tcp://localhost:4840"))
        self.label_12.setText(_translate("LDSDialog", "LDS registry text:"))
